export const GET_ALL_FILTERS_SUCCESS = 'GET_ALL_FILTERS_SUCCESS';
export const ADD_FILTER_TO_ACTIVE_FILTERS = 'ADD_FILTER_TO_ACTIVE_FILTERS';
export const REMOVE_FILTER_FROM_ACTIVE_FILTERS = 'REMOVE_FILTER_FROM_ACTIVE_FILTERS';
export const CHANGE_FILTER_IN_ACTIVE_FILTERS = 'CHANGE_FILTER_IN_ACTIVE_FILTERS';
export const REQUEST_DATA_WITH_FILTERS = 'REQUEST_DATA_WITH_FILTERS';
export const OPEN_FILTERS = 'OPEN_FILTERS';